name: raesan

services:
  raesan:
    container_name: raesan
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/raesan/node_modules
      - /usr/src/app/raesan-dbm/node_modules
      - ./target:/usr/src/app/target
    ports:
      - "8080:8080"
      - "9090:9090"
