name: raetest

services:
  raetest:
    container_name: raetest
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
