version: "3"

interval: 500ms

tasks:
  raesan:
    watch: true
    sources:
      - "raesan/**/*.rs"
      - "raesan/**/*.html"
      - "raesan/**/*.js"
    cmds:
      - cargo run -p raesan
    status:
      - "exit 1"
    cleanup:
      - rm -rf .task/checksum/raesan
  raesan-dbm:
    watch: true
    sources:
      - "raesan-dbm/**/*.rs"
      - "raesan-dbm/**/*.html"
      - "raesan-dbm/**/*.js"
    cmds:
      - cargo run -p raesan-dbm
    status:
      - "exit 1"
    cleanup:
      - rm -rf .task/checksum/raesan-dbm
  raesan-tw:
    dir: raesan
    cmds:
      - bun tailwindcss -i ./tailwind.css -o ./static/style.css --minify --watch
  raesan-dbm-tw:
    dir: raesan-dbm
    cmds:
      - bun tailwindcss -i ./tailwind.css -o ./static/style.css --minify --watch
