version: "3"

interval: 500ms

dotenv: [".env"]

tasks:
  # build the main application for production
  build:
    cmds:
      - docker build -t raesan:0.0.1 .

  # main raesan application
  raesan:
    watch: true
    sources:
      - "raesan/**/*.rs"
      - "raesan/**/*.html"
      - "raesan/**/*.js"
    cmds:
      - cargo run -p raesan serve --database $DATABASE_URL {{.CLI_ARGS}}
    status:
      - "exit 1"
    cleanup:
      - rm -rf .task/checksum/raesan
  # database manager
  raesan-dbm:
    watch: true
    sources:
      - "raesan-dbm/**/*.rs"
      - "raesan-dbm/**/*.html"
      - "raesan-dbm/**/*.js"
    cmds:
      - cargo run -p raesan-dbm serve --database $DATABASE_URL {{.CLI_ARGS}}
    status:
      - "exit 1"
    cleanup:
      - rm -rf .task/checksum/raesan-dbm
  # tailwind command for main raesan application
  raesan-tw:
    dir: raesan
    cmds:
      - bun tailwindcss -i ./tailwind.css -o ./static/style.css --minify --watch
  # tailwind command for database manager
  raesan-dbm-tw:
    dir: raesan-dbm
    cmds:
      - bun tailwindcss -i ./tailwind.css -o ./static/style.css --minify --watch
