[package]
name = "raesan-common"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
serde = { version = "1.0.170", features = ["derive"] }
